[tool.poetry]
name = "disjoint_set"
version = "0.7.0"
description = "Disjoint Set data structure implementation for Python"
authors = ["Maciej Rapacz <mmrapacz@protonmail.ch>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
