version: 2.1

jobs:
  base-template: &base_template
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            poetry --version
            make dev
            make test
  build-py37:
    <<: *base_template
    docker:
      - image: python:3.7
  build-py38: *base_template
workflows:
  version: 2
  build:
    jobs:
      - build-py37
      - build-py38
