version: 2
jobs:
  build:
    working_directory: ~/disjoint_set
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: |
            pip install --user -r requirements_dev.txt
            python -m doctest README.md disjoint_set/main.py
            python -m mypy -p disjoint_set --strict  --any-exprs-report .
            python -m coverage run -m unittest
            python -m coverage report
            python -m coverage html
            python -m coveralls
      - store_artifacts:
          path: htmlcov
      - store_test_results:
          path: any-exprs.txt