version: 2
jobs:
  base-template: &base_template
    docker:
      - image: python:3.8
    working_directory: ~/disjoint_set
    steps:
      - checkout
      - run:
          command: |
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            make dev
            make test
  build-py37:
    <<: *base_template
    docker:
      - image: python:3.7
  build-py38: *base_template
workflows:
  version: 2
  build:
    jobs:
      - build-py37
      - build-py38
